version: "3"
services:
    bot:
        build:
             .
        container_name: "py_bot"
        depends_on:
          - postgres
    postgres:
        image: "postgres:latest"
        container_name: "postgres_bot"
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=FinApp
        ports:
            - "5432:5432"
        volumes:
            - /home/alexov/bot/FinData/postgres:/var/lib/postgresql/data