version: "3"
services:
    bot:
        build:
             .
        container_name: "py_bot"
        depends_on:
          - postgres
    postgres:
        image: "postgres:latest"
        container_name: "postgres_bot"
        environment:
            - POSTGRES_USER='admin_bot'
            - POSTGRES_PASSWORD='admin_bot'
            - POSTGRES_DB='FinApp'
        ports:
            - "5432:5432"
        volumes:
            - ./data_app/postgres:/var/lib/postgresql/data